<MyScreen>:
    FloatLayout:
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            GridLayout:
                cols:5
                size_hint: 1., .1
                Button
                    text: 'button1'
                Button
                    text: 'button2'
                Button
                    text: 'button1'
                Button
                    text: 'button2'
                Button
                    text: 'button1'

