<MyScreen>:
    FloatLayout:
        GridLayout:
            size_hint: .8, .1
            pos_hint: {"x":.1, "top":.95}
            cols: 2
            rows: 1
            canvas.before:
                Color:
                    rgb: .6, .6, .6
                Rectangle:
                    size: self.size
            Button
                text: 'button1'
                background_color: (1., 0., 0., 1.)
            Button
                text: 'button2'
