<MyScreen>:
    FloatLayout:
        BoxLayout:
            orientation: 'horizontal'
            size_hint: .8, .1
            pos_hint: {"x":.1, "top":.95}
            canvas.before:
                Color:
                    rgb: .6, .6, .6
                Rectangle:
                    size: self.size
            Button
                text: 'button1'
            Button
                text: 'button2'
