<Screen2@Screen>:
    name: 'screen2'

    BoxLayout:
        orientation: "vertical"

        Label:
            text: "Screen 2"
        Button:
            text: "to main screen"
            on_press:
                app.root.current = "main_screen"
                root.manager.transition.direction = 'right'
        Button:
            text: "to screen 1"
            on_press:
                app.root.current = "screen1"
                root.manager.transition.direction = 'right'
